### ISSUE TITLE
Setup storybook

### ISSUE THREAD

**Issue by sebald** [reservix-ui/marigold#8]
Setup storybook to work with:

- typescript
- see if `@storybook/addon-docs` is an option for documentation
- make example story using https://storybook.js.org/docs/formats/component-story-format/ (as a smoke test)

**Comment by ti10le** [comment]
- [ ] add storybook for react (https://storybook.js.org/docs/guides/guide-react/)
- [ ] create .gitignore because of node_modules
- [ ] add react, react-dom, @babel/core, and babel-loader
- [ ] add typescript conifg like first design-system setup with:
- webpack.config.js add like this: https://github.com/storybookjs/storybook/issues/3346#issuecomment-467237732 --> storybook using with monorepo
- addons.js
- config.ts
